export type InjectionPointDefinition = {
  id: string;
  zona: string;
  nombre: string;
  cx: number;
  cy: number;
};

export type Gender = 'mujer' | 'hombre';

export const INJECTION_POINTS_MAP: Record<Gender, InjectionPointDefinition[]> = {
  hombre: [
    { id: 'h-f-1', zona: 'Frontal', nombre: 'Punto 1', cx: 400, cy: 174 },
    { id: 'h-f-2', zona: 'Frontal', nombre: 'Punto 2', cx: 253, cy: 177 },
    { id: 'h-f-3', zona: 'Frontal', nombre: 'Punto 3', cx: 304, cy: 178 },
    { id: 'h-f-4', zona: 'Frontal', nombre: 'Punto 4', cx: 352, cy: 177 },
    { id: 'h-f-5', zona: 'Frontal', nombre: 'Punto 5', cx: 449, cy: 175 },
    { id: 'h-f-6', zona: 'Frontal', nombre: 'Punto 6', cx: 491, cy: 177 },
    { id: 'h-f-7', zona: 'Frontal', nombre: 'Punto 7', cx: 536, cy: 177 },
    { id: 'h-f-8', zona: 'Frontal', nombre: 'Punto 8', cx: 248, cy: 231 },
    { id: 'h-f-9', zona: 'Frontal', nombre: 'Punto 9', cx: 307, cy: 233 },
    { id: 'h-f-10', zona: 'Frontal', nombre: 'Punto 10', cx: 353, cy: 233 },
    { id: 'h-f-11', zona: 'Frontal', nombre: 'Punto 11', cx: 402, cy: 233 },
    { id: 'h-f-12', zona: 'Frontal', nombre: 'Punto 12', cx: 449, cy: 233 },
    { id: 'h-f-13', zona: 'Frontal', nombre: 'Punto 13', cx: 493, cy: 231 },
    { id: 'h-f-14', zona: 'Frontal', nombre: 'Punto 14', cx: 539, cy: 234 },
    { id: 'h-g-1', zona: 'Glabela/Cejas', nombre: 'Punto 1', cx: 223, cy: 319 },
    { id: 'h-g-2', zona: 'Glabela/Cejas', nombre: 'Punto 2', cx: 371, cy: 310 },
    { id: 'h-g-3', zona: 'Glabela/Cejas', nombre: 'Punto 3', cx: 441, cy: 309 },
    { id: 'h-g-4', zona: 'Glabela/Cejas', nombre: 'Punto 4', cx: 585, cy: 312 },
    { id: 'h-g-5', zona: 'Glabela/Cejas', nombre: 'Punto 5', cx: 602, cy: 333 },
    { id: 'h-g-6', zona: 'Glabela/Cejas', nombre: 'Punto 6', cx: 198, cy: 343 },
    { id: 'h-g-7', zona: 'Glabela/Cejas', nombre: 'Punto 7', cx: 405, cy: 355 },
    { id: 'h-o-1', zona: 'Patas de gallo/Ojos', nombre: 'Punto 1', cx: 203, cy: 401 },
    { id: 'h-o-2', zona: 'Patas de gallo/Ojos', nombre: 'Punto 2', cx: 217, cy: 422 },
    { id: 'h-o-3', zona: 'Bunny lines', nombre: 'Punto 1', cx: 384, cy: 408 },
    { id: 'h-o-4', zona: 'Bunny lines', nombre: 'Punto 2', cx: 426, cy: 407 },
    { id: 'h-o-5', zona: 'Patas de gallo/Ojos', nombre: 'Punto 3', cx: 579, cy: 423 },
    { id: 'h-o-6', zona: 'Patas de gallo/Ojos', nombre: 'Punto 4', cx: 600, cy: 404 },
    { id: 'h-o-7', zona: 'Patas de gallo/Ojos', nombre: 'Punto 5', cx: 239, cy: 437 },
    { id: 'h-o-8', zona: 'Patas de gallo/Ojos', nombre: 'Punto 6', cx: 381, cy: 443 },
    { id: 'h-o-9', zona: 'Patas de gallo/Ojos', nombre: 'Punto 7', cx: 430, cy: 441 },
    { id: 'h-o-10', zona: 'Patas de gallo/Ojos', nombre: 'Punto 8', cx: 551, cy: 439 },
    { id: 'h-l-1', zona: 'Mejillas/Labios', nombre: 'Punto 1', cx: 356, cy: 487 },
    { id: 'h-l-2', zona: 'Mejillas/Labios', nombre: 'Punto 2', cx: 405, cy: 503 },
    { id: 'h-l-3', zona: 'Mejillas/Labios', nombre: 'Punto 3', cx: 457, cy: 483 },
    { id: 'h-l-4', zona: 'Mejillas/Labios', nombre: 'Punto 4', cx: 213, cy: 581 },
    { id: 'h-l-5', zona: 'Mejillas/Labios', nombre: 'Punto 5', cx: 355, cy: 557 },
    { id: 'h-l-6', zona: 'Mejillas/Labios', nombre: 'Punto 6', cx: 459, cy: 555 },
    { id: 'h-l-7', zona: 'Mejillas/Labios', nombre: 'Punto 7', cx: 589, cy: 585 },
    { id: 'h-l-8', zona: 'Mejillas/Labios', nombre: 'Punto 8', cx: 218, cy: 605 },
    { id: 'h-l-9', zona: 'Mejillas/Labios', nombre: 'Punto 9', cx: 245, cy: 606 },
    { id: 'h-l-10', zona: 'Mejillas/Labios', nombre: 'Punto 10', cx: 325, cy: 602 },
    { id: 'h-l-11', zona: 'Mejillas/Labios', nombre: 'Punto 11', cx: 349, cy: 596 },
    { id: 'h-l-12', zona: 'Mejillas/Labios', nombre: 'Punto 12', cx: 463, cy: 597 },
    { id: 'h-l-13', zona: 'Mejillas/Labios', nombre: 'Punto 13', cx: 482, cy: 602 },
    { id: 'h-l-14', zona: 'Mejillas/Labios', nombre: 'Punto 14', cx: 558, cy: 615 },
    { id: 'h-l-15', zona: 'Mejillas/Labios', nombre: 'Punto 15', cx: 587, cy: 610 },
    { id: 'h-m-1', zona: 'Mentón/Masetero', nombre: 'Punto 1', cx: 316, cy: 687 },
    { id: 'h-m-2', zona: 'Mentón/Masetero', nombre: 'Punto 2', cx: 502, cy: 690 },
    { id: 'h-m-3', zona: 'Mentón/Masetero', nombre: 'Punto 3', cx: 248, cy: 757 },
    { id: 'h-m-4', zona: 'Mentón/Masetero', nombre: 'Punto 4', cx: 404, cy: 746 },
    { id: 'h-m-5', zona: 'Mentón/Masetero', nombre: 'Punto 5', cx: 554, cy: 751 },
    { id: 'h-p-1', zona: 'Platisma/Cuello', nombre: 'Punto 1', cx: 236, cy: 837 },
    { id: 'h-p-2', zona: 'Platisma/Cuello', nombre: 'Punto 2', cx: 337, cy: 808 },
    { id: 'h-p-3', zona: 'Platisma/Cuello', nombre: 'Punto 3', cx: 481, cy: 810 },
    { id: 'h-p-4', zona: 'Platisma/Cuello', nombre: 'Punto 4', cx: 587, cy: 837 },
    { id: 'h-p-5', zona: 'Platisma/Cuello', nombre: 'Punto 5', cx: 338, cy: 869 },
    { id: 'h-p-6', zona: 'Platisma/Cuello', nombre: 'Punto 6', cx: 478, cy: 873 },
    { id: 'h-p-7', zona: 'Platisma/Cuello', nombre: 'Punto 7', cx: 211, cy: 916 },
    { id: 'h-p-8', zona: 'Platisma/Cuello', nombre: 'Punto 8', cx: 613, cy: 902 },
    { id: 'h-p-9', zona: 'Platisma/Cuello', nombre: 'Punto 9', cx: 337, cy: 939 },
    { id: 'h-p-10', zona: 'Platisma/Cuello', nombre: 'Punto 10', cx: 491, cy: 943 }
  ],
  mujer: [
    { id: 'm-f-1', zona: 'Frontal', nombre: 'Punto 1', cx: 215, cy: 191 },
    { id: 'm-f-2', zona: 'Frontal', nombre: 'Punto 2', cx: 271, cy: 188 },
    { id: 'm-f-3', zona: 'Frontal', nombre: 'Punto 3', cx: 347, cy: 187 },
    { id: 'm-f-4', zona: 'Frontal', nombre: 'Punto 4', cx: 438, cy: 191 },
    { id: 'm-f-5', zona: 'Frontal', nombre: 'Punto 5', cx: 491, cy: 187 },
    { id: 'm-f-6', zona: 'Frontal', nombre: 'Punto 6', cx: 547, cy: 182 },
    { id: 'm-f-7', zona: 'Frontal', nombre: 'Punto 7', cx: 242, cy: 235 },
    { id: 'm-f-8', zona: 'Frontal', nombre: 'Punto 8', cx: 315, cy: 236 },
    { id: 'm-f-9', zona: 'Frontal', nombre: 'Punto 9', cx: 403, cy: 238 },
    { id: 'm-f-10', zona: 'Frontal', nombre: 'Punto 10', cx: 466, cy: 238 },
    { id: 'm-f-11', zona: 'Frontal', nombre: 'Punto 11', cx: 534, cy: 234 },
    { id: 'm-g-1', zona: 'Glabela/Cejas', nombre: 'Punto 1', cx: 195, cy: 331 },
    { id: 'm-g-2', zona: 'Glabela/Cejas', nombre: 'Punto 2', cx: 229, cy: 304 },
    { id: 'm-g-3', zona: 'Glabela/Cejas', nombre: 'Punto 3', cx: 367, cy: 303 },
    { id: 'm-g-4', zona: 'Glabela/Cejas', nombre: 'Punto 4', cx: 451, cy: 304 },
    { id: 'm-g-5', zona: 'Glabela/Cejas', nombre: 'Punto 5', cx: 593, cy: 304 },
    { id: 'm-g-6', zona: 'Glabela/Cejas', nombre: 'Punto 6', cx: 617, cy: 334 },
    { id: 'm-g-7', zona: 'Glabela/Cejas', nombre: 'Punto 7', cx: 417, cy: 345 },
    { id: 'm-o-1', zona: 'Patas de gallo/Ojos', nombre: 'Punto 1', cx: 199, cy: 399 },
    { id: 'm-o-2', zona: 'Patas de gallo/Ojos', nombre: 'Punto 2', cx: 221, cy: 425 },
    { id: 'm-o-3', zona: 'Bunny lines', nombre: 'Punto 1', cx: 383, cy: 405 },
    { id: 'm-o-4', zona: 'Bunny lines', nombre: 'Punto 2', cx: 437, cy: 406 },
    { id: 'm-o-5', zona: 'Patas de gallo/Ojos', nombre: 'Punto 3', cx: 611, cy: 408 },
    { id: 'm-o-6', zona: 'Patas de gallo/Ojos', nombre: 'Punto 4', cx: 255, cy: 444 },
    { id: 'm-o-7', zona: 'Patas de gallo/Ojos', nombre: 'Punto 5', cx: 382, cy: 444 },
    { id: 'm-o-8', zona: 'Patas de gallo/Ojos', nombre: 'Punto 6', cx: 434, cy: 444 },
    { id: 'm-o-9', zona: 'Patas de gallo/Ojos', nombre: 'Punto 7', cx: 550, cy: 449 },
    { id: 'm-o-10', zona: 'Patas de gallo/Ojos', nombre: 'Punto 8', cx: 585, cy: 438 },
    { id: 'm-l-1', zona: 'Mejillas/Labios', nombre: 'Punto 1', cx: 367, cy: 484 },
    { id: 'm-l-2', zona: 'Mejillas/Labios', nombre: 'Punto 2', cx: 452, cy: 484 },
    { id: 'm-l-3', zona: 'Mejillas/Labios', nombre: 'Punto 3', cx: 214, cy: 566 },
    { id: 'm-l-4', zona: 'Mejillas/Labios', nombre: 'Punto 4', cx: 356, cy: 591 },
    { id: 'm-l-5', zona: 'Mejillas/Labios', nombre: 'Punto 5', cx: 360, cy: 551 },
    { id: 'm-l-6', zona: 'Mejillas/Labios', nombre: 'Punto 6', cx: 409, cy: 588 },
    { id: 'm-l-7', zona: 'Mejillas/Labios', nombre: 'Punto 7', cx: 463, cy: 554 },
    { id: 'm-l-8', zona: 'Mejillas/Labios', nombre: 'Punto 8', cx: 600, cy: 574 },
    { id: 'm-l-9', zona: 'Mejillas/Labios', nombre: 'Punto 9', cx: 327, cy: 600 },
    { id: 'm-l-10', zona: 'Mejillas/Labios', nombre: 'Punto 10', cx: 476, cy: 595 },
    { id: 'm-l-11', zona: 'Mejillas/Labios', nombre: 'Punto 11', cx: 499, cy: 605 },
    { id: 'm-m-1', zona: 'Mentón/Masetero', nombre: 'Punto 1', cx: 228, cy: 633 },
    { id: 'm-m-2', zona: 'Mentón/Masetero', nombre: 'Punto 2', cx: 273, cy: 631 },
    { id: 'm-m-3', zona: 'Mentón/Masetero', nombre: 'Punto 3', cx: 528, cy: 620 },
    { id: 'm-m-4', zona: 'Mentón/Masetero', nombre: 'Punto 4', cx: 588, cy: 628 },
    { id: 'm-m-5', zona: 'Mentón/Masetero', nombre: 'Punto 5', cx: 348, cy: 639 },
    { id: 'm-m-6', zona: 'Mentón/Masetero', nombre: 'Punto 6', cx: 380, cy: 655 },
    { id: 'm-m-7', zona: 'Mentón/Masetero', nombre: 'Punto 7', cx: 442, cy: 653 },
    { id: 'm-m-8', zona: 'Mentón/Masetero', nombre: 'Punto 8', cx: 481, cy: 636 },
    { id: 'm-m-9', zona: 'Mentón/Masetero', nombre: 'Punto 9', cx: 281, cy: 684 },
    { id: 'm-m-10', zona: 'Mentón/Masetero', nombre: 'Punto 10', cx: 330, cy: 696 },
    { id: 'm-m-11', zona: 'Mentón/Masetero', nombre: 'Punto 11', cx: 496, cy: 686 },
    { id: 'm-m-12', zona: 'Mentón/Masetero', nombre: 'Punto 12', cx: 543, cy: 678 },
    { id: 'm-m-13', zona: 'Mentón/Masetero', nombre: 'Punto 13', cx: 412, cy: 739 },
    { id: 'm-m-14', zona: 'Mentón/Masetero', nombre: 'Punto 14', cx: 527, cy: 752 },
    { id: 'm-m-15', zona: 'Mentón/Masetero', nombre: 'Punto 15', cx: 290, cy: 764 },
    { id: 'm-p-1', zona: 'Platisma/Cuello', nombre: 'Punto 1', cx: 349, cy: 791 },
    { id: 'm-p-2', zona: 'Platisma/Cuello', nombre: 'Punto 2', cx: 463, cy: 797 },
    { id: 'm-p-3', zona: 'Platisma/Cuello', nombre: 'Punto 3', cx: 274, cy: 832 },
    { id: 'm-p-4', zona: 'Platisma/Cuello', nombre: 'Punto 4', cx: 543, cy: 838 },
    { id: 'm-p-5', zona: 'Platisma/Cuello', nombre: 'Punto 5', cx: 347, cy: 850 },
    { id: 'm-p-6', zona: 'Platisma/Cuello', nombre: 'Punto 6', cx: 461, cy: 855 },
    { id: 'm-p-7', zona: 'Platisma/Cuello', nombre: 'Punto 7', cx: 255, cy: 889 },
    { id: 'm-p-8', zona: 'Platisma/Cuello', nombre: 'Punto 8', cx: 346, cy: 896 },
    { id: 'm-p-9', zona: 'Platisma/Cuello', nombre: 'Punto 9', cx: 454, cy: 908 },
    { id: 'm-p-10', zona: 'Platisma/Cuello', nombre: 'Punto 10', cx: 555, cy: 891 },
    { id: 'm-p-11', zona: 'Platisma/Cuello', nombre: 'Punto 11', cx: 220, cy: 955 },
    { id: 'm-p-12', zona: 'Platisma/Cuello', nombre: 'Punto 12', cx: 341, cy: 963 },
    { id: 'm-p-13', zona: 'Platisma/Cuello', nombre: 'Punto 13', cx: 455, cy: 965 },
    { id: 'm-p-14', zona: 'Platisma/Cuello', nombre: 'Punto 14', cx: 583, cy: 963 }
  ]
};

// Combinación única de todas las zonas para el resumen
export const ZONAS_INYECCION = Array.from(
  new Set([
    ...INJECTION_POINTS_MAP.hombre.map(p => p.zona),
    ...INJECTION_POINTS_MAP.mujer.map(p => p.zona)
  ])
);

// Mantenemos este export para compatibilidad con el esquema de datos (store)
// pero ahora incluiremos TODOS los puntos posibles de ambos géneros.
export const INJECTION_POINTS: InjectionPointDefinition[] = [
  ...INJECTION_POINTS_MAP.hombre,
  ...INJECTION_POINTS_MAP.mujer
];
